### ISSUE TITLE
老板接收技术咨询部

### ISSUE THREAD

**Issue by wuyaoyao-2020** [breakstring/esp32-hub75-devkit#2]
有项目想请老板出山，定制是否可以

**Comment by breakstring** [comment]
> 有项目想请老板出山，定制是否可以

呃。。。我就压根不是专业的硬件开发人员，做这个板子也就是自己业余时间玩玩而已。。。您真要做项目还是找其他专业人士比较好耶。

**Comment by Loufey** [comment]
src/main.cpp:106:24: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'; did you mean 'drawPixelRGB888'?
           dma_display->drawPixelRGB565(x + xOffset, y, usTemp[xOffset]);

老板，编译源码的时候报错。没有定义drawPixelRGB56函数，是否需要安装新的库还是需要怎么操作 TnT

**Comment by breakstring** [comment]
> src/main.cpp:106:24: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'; did you mean 'drawPixelRGB888'? dma_display->drawPixelRGB565(x + xOffset, y, usTemp[xOffset]);
> 
> 老板，编译源码的时候报错。没有定义drawPixelRGB56函数，是否需要安装新的库还是需要怎么操作 TnT

呃。。。我这个项目比较老了，不知道是不是那个驱动的库的新版本里去掉了这个函数？您可能得要自己研究下这个库了。或者改一下platformio.ini那个文件，将这个库指定成我原来的那个版本（我这个配置里的写法的含义是。。。不要小于这个版本。。。）
mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^2.0.2
我印象中把这个上箭头去掉就是指定这个版本吧？
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA

**Comment by Loufey** [comment]
> > src/main.cpp:106:24: error: 'class MatrixPanel_I2S_DMA' has no member named 'drawPixelRGB565'; did you mean 'drawPixelRGB888'? dma_display->drawPixelRGB565(x + xOffset, y, usTemp[xOffset]);
> > 老板，编译源码的时候报错。没有定义drawPixelRGB56函数，是否需要安装新的库还是需要怎么操作 TnT
> 
> 呃。。。我这个项目比较老了，不知道是不是那个驱动的库的新版本里去掉了这个函数？您可能得要自己研究下这个库了。或者改一下platformio.ini那个文件，将这个库指定成我原来的那个版本（我这个配置里的写法的含义是。。。不要小于这个版本。。。） mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^2.0.2 我印象中把这个上箭头去掉就是指定这个版本吧？ https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA

ok 我找到2.0.0版本的代码里面有。确实是原作者删掉了。不知道为嘛。
// For adafruit
inline void MatrixPanel_I2S_DMA::drawPixelRGB565(int16_t x, int16_t y, uint16_t color) 
{
  uint8_t r = ((((color >> 11) & 0x1F) * 527) + 23) >> 6;
  uint8_t g = ((((color >> 5) & 0x3F) * 259) + 33) >> 6;
  uint8_t b = (((color & 0x1F) * 527) + 23) >> 6;
  
  updateMatrixDMABuffer( x, y, r, g, b);
}
