### ISSUE TITLE
大佬，非常喜欢你这个产品，还有货没，我下单了

### ISSUE THREAD

**Issue by jd3096-mpy** [breakstring/esp32-hub75-devkit#3]
我看淘宝店已经关了，微信商店还在，还有货吗，能不能下单，谢谢

**Comment by breakstring** [comment]
> 我看淘宝店已经关了，微信商店还在，还有货吗，能不能下单，谢谢

呃。。。没有几块了，本想着就留几个当个纪念品。我都忘了还有个微信商店，汗。。。。等我回家看看哈。。。。

**Comment by breakstring** [comment]
> 我看淘宝店已经关了，微信商店还在，还有货吗，能不能下单，谢谢

我看家里还有几块，本想着如果你感兴趣的话微信商店里给你改个1元价格不包邮的给你发过去1块。结果还改不了价格，貌似微信商店现在个人账号都要改成企业账号才行。。。懒得折腾了。好像Github不能发私信？如果你需要的话去淘宝上给我发个私信你的地址，我给你寄一块吧。
